services:
  - docker:dind

variables:
  GITHUB_REF: $CI_COMMIT_SHA
  
stages:
  - build

build:
  image: registry.gitlab.com/tokend/deployment/docker-build:latest
  stage: build
  tags:
    - tokend
  script:
    - ci-little-helper set-pending build
    - STATE=$(.ci/build.sh)
    - ci-little-helper set-state $STATE build